### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by thesudoman** [cradlepoint/api-samples#34]
I am attempting to use your script to modify a group where a router is stored. I see your script is created with the intention of modifying a router so I made a few changes to get it to modify the group but am getting the below response when I attempt to run:

Traceback (most recent call last):
  File "/home/user/github/netcloudapi/api-samples/configuration/samples/dmvpn_maker/config_pusher.py", line 150, in <module>
    push_configs()
  File "/home/user/github/netcloudapi/api-samples/configuration/samples/dmvpn_maker/config_pusher.py", line 111, in push_configs
    cfg_id = cfg.json().get("data")[0].get("id")
TypeError: 'NoneType' object is not subscriptable

**Comment by thesudoman** [comment]
It appears to have been an issue on my end trying to convert the syntax over to support group modification. 

Side note, this script is amazing and I appreciate you publishing it! Was a huge help.
